@echo off
echo Running Cypress tests for bao-cao-thong-ke...

echo Running overview tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/overview.cy.js"

echo Running filters tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/filters.cy.js"

echo Running chart tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/chart.cy.js"

echo Running api tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/api.cy.js"

echo Running edge-cases tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/edge-cases.cy.js"

echo Running responsive tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/responsive.cy.js"

echo Running index tests...
npx cypress run --spec "cypress/e2e/bao-cao-thong-ke/index.cy.js"

echo All tests completed!
